### ISSUE TITLE
Freezing the Header and First column

### ISSUE THREAD

**Issue by nikunj0407** [volosoft/jtable#1184]
I want to freeze the header and the first column of my table. I've tried http://jsfiddle.net/feLXX/2/ for freezing the header. Didn't work though as expected.

But the output isn't in place. My thead and tbody data are not aligned as expected.

Need the fix on urgent basis as our client needs this.

Thnx

**Comment by tchoulihan** [comment]
Here's what worked for me:

```css
$('.jtable').wrap('<div class="jtable-main-container scroll-content" />');    
and

.scroll-content {
     overflow-y: auto;
    width:100%;
 }
div.jtable-main-container {
  height:100%;
}
```
