### ISSUE TITLE
Jtable Header Fixed

### ISSUE THREAD

**Issue by Mansaraa** [volosoft/jtable#1339]
When i set 500 record per page in Jtable. I want to set my jtable header fix and i can scroll record but fixed header..

**Comment by tchoulihan** [comment]
Here's what worked for me.

Here's what worked for me:

```css
$('.jtable').wrap('<div class="jtable-main-container scroll-content" />');    
and

.scroll-content {
     overflow-y: auto;
    width:100%;
 }
div.jtable-main-container {
  height:100%;
}
```
