### ISSUE TITLE
Jtable with scrolling

### ISSUE THREAD

**Issue by galastur** [volosoft/jtable#252]
Hi guys,

Awesome tool. I would just like to suggest making the table scroll-able. Just the content (header and footer should be fixed). I believe it will be a really nice feature to have.

Thanks

**Comment by tchoulihan** [comment]
Here's what worked for me:

```css
$('.jtable').wrap('<div class="jtable-main-container scroll-content" />');    
and

.scroll-content {
     overflow-y: auto;
    width:100%;
 }
div.jtable-main-container {
  height:100%;
}
```
