### ISSUE TITLE
How i can make my jtable scrollable with fixed header table?

### ISSUE THREAD

**Issue by hoquangthaiholy** [volosoft/jtable#830]
How i can make my jtable scrollable with fixed header table?

**Comment by tchoulihan** [comment]
Here's what worked for me:

```css
$('.jtable').wrap('<div class="jtable-main-container scroll-content" />');    
and

.scroll-content {
     overflow-y: auto;
    width:100%;
 }
div.jtable-main-container {
  height:100%;
}
```
